// forecast
export const CHOICE_DEFAULT_SUPPLIER_ITEM = 'CHOICE_DEFAULT_SUPPLIER_ITEM';
export const CHOICE_WAREHOUSE_ITEM = 'CHOICE_WAREHOUSE_ITEM';
export const CHOICE_SUPPPLIER_ITEM = 'CHOICE_SUPPPLIER_ITEM';
export const CHOICE_TAG_ITEM = 'CHOICE_TAG_ITEM';
// inventoryHistory
export const CHOICE_BRAND_ITEM = 'CHOICE_BRAND_ITEM';
export const CHOICE_REASON_ITEM = 'CHOICE_REASON_ITEM';
export const CHOICE_EMPLOYEE_ITEM = 'CHOICE_EMPLOYEE_ITEM';
export const CHOICE_CHANGE_REASON_ITEM = 'CHOICE_CHANGE_REASON_ITEM';
// returns
export const CHOICE_RETURN_STATUS_ITEM = 'CHOICE_RETURN_STATUS_ITEM';
export const CHOICE_RETURN_REASON_ITEM = 'CHOICE_RETURN_REASON_ITEM';
export const CHOICE_RETURN_PAID_ITEM = 'CHOICE_RETURN_PAID_ITEM';
export const CHOICE_CUSTOMER_TYPE_ITEM = 'CHOICE_CUSTOMER_TYPE_ITEM';
// sales
export const CHOICE_CHANNEL_ITEM = 'CHOICE_CHANNEL_ITEM';
export const CHOICE_ORDER_STATUS_ITEM = 'CHOICE_ORDER_STATUS_ITEM';
export const CHOICE_ENABLED_DELIVERY_COST_OPTION_ITEM = 'CHOICE_ENABLED_DELIVERY_COST_OPTION_ITEM';

export const SET_FILTERS_FROM_LOCATION = 'SET_FILTERS_FROM_LOCATION';